name: Test bot installation script on different operating systems
on:
  push:
    branches: all
  pull_request:
    branches: [ main ]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test bot script on ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # check for linting errors
      - name: Check for linting errors
        run: |
          sudo apt-get update
          sudo apt install -y shellcheck
          chmod +x install.sh
          shellcheck install.sh

      - name: Run shell script
        run: ./install.sh       

